/*
Group 19 Compiler Construction Submission
	Rajat Payghan (2021A7PS2218P)
	Rudra Goyal (2021A7PS0708P)
	Samraddh Saxena (2021A7PS1455P)
	Aditya Patel (2021A7PS2433P)
	Bhagwati Iyer (2021A7PS0685P)
	Jai Bothra (2021A7PS0015P)
*/

#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include "lexer.h"
#include <time.h>
// #include "lexer.c"
#include "parser.h"

int print_options()
{
	printf("\n\nSelect one of the following options (please type in an integer) :\n");
	printf("Press 0 : To exit the program\n");
	printf("Press 1 : For removal of comments\n");
	printf("Press 2 : For printing the token list generated by the lexer\n");
	printf("Press 3 : Verify the syntactic correctness of the input source code and printing the parse tree\n");
	printf("Press 4 : For printing the total time taken by the project code of lexer\n");
}

void print_intro()
{
	printf("FIRST and FOLLOW sets automated.\n");
	printf("Only Lexical analyzer module developed\n");
	printf("Both lexical and syntax analysis modules implemented\n");
	printf("Modules compile but give segmentation fault\n");
	printf("Modules work with testcases 2, 3 and 4 only\n");
	printf("Parse tree could not be constructed\n");
	printf("\n");
}

void print_token_list(FILE *fp, symTable *map, lex_header *lex_list)
{
	getStream(fp);
	print(fp, map, lex_list);
}

int main(int argc, char const *argv[])
{
	clock_t t;
	int f;
	symTable *map = initsymbolTable();
	lex_header *lex_list = create_Larray();
	int option;
	float t1 = -1, t2 = -1, t3 = -1;
	char *testfile = argv[1];
	char *outfile = argv[2];
	FILE *fp;
	fp = fopen(testfile, "r");
	while (1)
	{
		print_options();
		scanf("%d", &option);
		switch (option)
		{
		case 0:
			printf("0\n");
			break;
		case 1:
			printf("1\n");
			removeComments(fp);
			break;
		case 2:
			printf("2\n");
			print_token_list(fp, map, lex_list);
			break;
		case 3:
			printf("3\n");
			mainParser(fp, outfile);

			break;
		case 4:
			printf("4\n");
			t = clock();
			print_token_list(fp, map, lex_list);
			print_token_list(fp, map, lex_list);
			t = clock() - t;
			printf("TIME ==  (%f seconds).\n", ((float)t) / CLOCKS_PER_SEC);
			break;
		default:
			printf("-----------------Please choose a Valid Option-----------------\n");
		}
		rewind(fp);
		if (option == 0)
		{
			printf("----------------------------Exiting--------------------------\n");
			break;
		}
	}
}